version: "3.5"
services:
  centos7apcu:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
  stream8apcu:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream