version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.7

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  apcubuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7apcu
          build_service: centos7apcu
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcu
          build_service: centos8apcu
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7apcuphp73
          build_file: docker-compose.php73.yml
          build_service: centos7apcuphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcuphp73
          build_file: docker-compose.php73.yml
          build_service: centos8apcuphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7apcuphp80
          build_file: docker-compose.php80.yml
          build_service: centos7apcuphp80
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcuphp80
          build_file: docker-compose.php80.yml
          build_service: centos8apcuphp80
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7apcuphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos7apcuphp74build
          requires:
            - centos7apcu
      - docker-rpmbuild/image:
          name: centos8apcuphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos8apcuphp74build
          requires:
            - centos8apcu
      - docker-rpmbuild/image:
          name: centos7apcuphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos7apcuphp73build
          requires:
            - centos7apcuphp73
      - docker-rpmbuild/image:
          name: centos8apcuphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos8apcuphp73build
          requires:
            - centos8apcuphp73
      - docker-rpmbuild/image:
          name: centos7apcuphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos7apcuphp80build
          requires:
            - centos7apcuphp80
      - docker-rpmbuild/image:
          name: centos8apcuphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos8apcuphp80build
          requires:
            - centos8apcuphp80

